version: "3.8"
services:
  postgres:
    image: postgres
    container_name: postgres
    volumes:
      - ./domain/data:/var/lib/postgresql/data
      - ./domain/sql/ddl.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - 5423:5432    
    environment:            
      - POSTGRES_DB=teste_nuti
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres