version: "3.8"
services:
  
  backend_tests:
    image: node:14.15.1
    container_name: backend_tests
    volumes:
      - ./domain/src:/home/domain/src
      - ./.env:/home/domain/src/.env
    working_dir: /home/domain/src
    command: ["npm", "run", "test"]      
    depends_on:
      - postgres
    links:
      - "postgres:${DB_HOST}"

  backend:
    image: node:14.15.1
    container_name: backend    
    volumes:
      - ./domain/src:/home/domain/src
      - ./.env:/home/domain/src/.env
    working_dir: /home/domain/src
    command: ["npm", "run", "start"]
    ports:
      - "${APP_PORT}:3000"    
    depends_on:
      - postgres
    links:
      - "postgres:${DB_HOST}"

  postgres:
    image: postgres
    container_name: postgres
    volumes:
      - ./domain/data:/var/lib/postgresql/data
      - ./domain/sql/ddl.sql:/docker-entrypoint-initdb.d/init.sql
      - ./domain/sql/test_ddl.sql:/docker-entrypoint-initdb.d/init_test_db.sql    
    environment:            
      - "POSTGRES_DB=${DB_DATABASE}"
      - "POSTGRES_PASSWORD=${DB_PASSWORD}"
      - "POSTGRES_USER=${DB_USER}"